force-app/main/default/objects/DEVICE_MNG__x/DEVICE_MNG__x.object-meta.xml
<CustomObject>
    <description>DEVICE_MNG</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>DEVICE_MNG</externalName>
    <label>機器管理</label>
</CustomObject>

force-app/main/default/objects/DEVICE_MNG__x/fields/device_mng_id__c.field-meta.xml
<CustomField>
    <fullName>device_mng_id__c</fullName>
    <description>device_mng_id</description>
    <externalDeveloperName>device_mng_id</externalDeveloperName>
    <label>機器管理ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_ERROR_INF__x/SIGHTS_CAMERA_ERROR_INF__x.object-meta.xml
<CustomObject>
    <description>SIGHTS_CAMERA_ERROR_INF</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>SIGHTS_CAMERA_ERROR_INF</externalName>
    <label>Sightsカメラ異常状態</label>
</CustomObject>

force-app/main/default/objects/SIGHTS_CAMERA_ERROR_INF__x/fields/shock__c.field-meta.xml
<CustomField>
    <fullName>shock__c</fullName>
    <description>shock</description>
    <externalDeveloperName>shock</externalDeveloperName>
    <label>shock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_ERROR_INF__x/fields/signal_lost__c.field-meta.xml
<CustomField>
    <fullName>signal_lost__c</fullName>
    <description>signal_lost</description>
    <externalDeveloperName>signal_lost</externalDeveloperName>
    <label>signal_lost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_ERROR_INF__x/fields/tamper__c.field-meta.xml
<CustomField>
    <fullName>tamper__c</fullName>
    <description>tamper</description>
    <externalDeveloperName>tamper</externalDeveloperName>
    <label>tamper</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_ERROR_INF__x/fields/temperature__c.field-meta.xml
<CustomField>
    <fullName>temperature__c</fullName>
    <description>temperature</description>
    <externalDeveloperName>temperature</externalDeveloperName>
    <label>temperature</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/SIGHTS_CAMERA_INF__x.object-meta.xml
<CustomObject>
    <description>SIGHTS_CAMERA_INF</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>SIGHTS_CAMERA_INF</externalName>
    <label>Sightsカメラ情報</label>
</CustomObject>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/fields/device_mng_id__c.field-meta.xml
<CustomField>
    <fullName>device_mng_id__c</fullName>
    <description>device_mng_id</description>
    <externalDeveloperName>device_mng_id</externalDeveloperName>
    <label>機器管理</label>
    <length>36</length>
    <referenceTo>DEVICE_MNG__x</referenceTo>
    <relationshipLabel>Sightsカメラ情報</relationshipLabel>
    <relationshipName>sights_camera_inf_LKUP</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/fields/sights_camera_inf_id__c.field-meta.xml
<CustomField>
    <fullName>sights_camera_inf_id__c</fullName>
    <description>sights_camera_inf_id</description>
    <externalDeveloperName>sights_camera_inf_id</externalDeveloperName>
    <label>Sightsカメラ情報ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RMS_CameraErrorListCtrl.cls
public with sharing class RMS_CameraErrorListCtrl {
  public class UpdateResult {
    public Boolean isSuccess;
    public String message;
    public SIGHTS_CAMERA_ERROR_INF__x record;

    public UpdateResult(
      Boolean isSuccess,
      String message,
      SIGHTS_CAMERA_ERROR_INF__x record
    ) {
      this.isSuccess = isSuccess;
      this.message = message;
      this.record = record;
    }
  }

  /**
   * Sightsカメラ情報レコードの取得
   *
   * @param recordId 画面表示している機器管理レコードのId
   * @return 機器管理レコードの外部Idを持つSightsカメラ情報レコードのList
   */
  @AuraEnabled(cacheable=true)
  public static List<SIGHTS_CAMERA_INF__x> getSightsCameraInfList(
    String recordId
  ) {
    // デバイス管理の取得
    List<DEVICE_MNG__x> deviceMngList = RMS_Util.getDeviceMng(recordId);

    // Sightsカメラ情報の取得
    List<SIGHTS_CAMERA_INF__x> sightsCameraInfList = RMS_Util.getSightsCameraInfListByDeviceMngId(
      deviceMngList[0]
    );

    return sightsCameraInfList;
  }

  /**
   * Sightsカメラ異常状態レコードの取得
   *
   * @param sightsCameraInfList getSightsCameraInfListByDeviceMngId で取得したSightsカメラ情報レコードのList
   * @return Sightsカメラ異常状態レコードのList
   */
  @AuraEnabled(cacheable=true)
  public static SIGHTS_CAMERA_ERROR_INF__x getSightsCameraErrorInf(
    List<SIGHTS_CAMERA_INF__x> sightsCameraInfList
  ) {
    // Sightsカメラ異常状態の取得
    List<SIGHTS_CAMERA_ERROR_INF__x> sigthsCameraErrorInfList = getSightsCameraErrorInfListByCameraInf(
      sightsCameraInfList[0]
    );

    if (sigthsCameraErrorInfList.size() > 0) {
      return sigthsCameraErrorInfList[0];
    }
    return null;
  }

  /**
   * Sightsカメラ異常状態レコードの取得
   * device_mng_id__c を使用したいため取得している
   *
   * @param sightsCameraInf 画面表示している機器管理レコードに紐づくSightsカメラ情報レコード
   * @return Sightsカメラ情報レコードに紐づくSightsカメラ異常状態レコードList（1件のみ）
   */
  private static List<SIGHTS_CAMERA_ERROR_INF__x> getSightsCameraErrorInfListByCameraInf(
    SIGHTS_CAMERA_INF__x sightsCameraInf
  ) {
    // prettier-ignore
    List<SIGHTS_CAMERA_ERROR_INF__x> sigthsCameraErrorInfList = [
      SELECT
        Id
        , ExternalId
        , shock__c
        , signal_lost__c
        , tamper__c
        , temperature__c
      FROM
        SIGHTS_CAMERA_ERROR_INF__x
      WHERE
        sights_camera_inf_id__c = :sightsCameraInf.sights_camera_inf_id__c
    ];
    return sigthsCameraErrorInfList;
  }

  /**
   * Sightsカメラ異常状態レコードの更新（復旧用）
   *
   * @param sigthsCameraErrorInfList getSightsCameraInfListByDeviceMngId で取得したSightsカメラ情報レコードのList
   * @return Sightsカメラ異常状態レコードのList
   */
  /*
  @AuraEnabled(cacheable=true)
  public static String updateSightsCameraErrorInf(
    SIGHTS_CAMERA_ERROR_INF__x sigthsCameraErrorInf
  ) {
    Boolean isSuccess = false;
    String message = '';

    try {
      // 外部オブジェクトのDML操作は、ooAsync or ooImmediateで行う
      //Database.SaveResult sr = Database.updateAsync(sigthsCameraErrorInf);
      Database.SaveResult sr = Database.updateImmediate(sigthsCameraErrorInf);
      if (!sr.isSuccess()) {
        String locator = Database.getAsyncLocator(sr);
        message = '更新失敗 : ' + locator;
      } else {
        isSuccess = true;
        message = 'Sightsカメラ異常状態レコードの更新に成功しました。';
      }
    } catch (Exception e) {
      message = '更新失敗 : ' + e.getMessage();
    }

    return JSON.serialize(
      new UpdateResult(isSuccess, message, sigthsCameraErrorInf)
    );
  }
  */
  @AuraEnabled(cacheable=true)
  public static SIGHTS_CAMERA_ERROR_INF__x updateSightsCameraErrorInf(
    SIGHTS_CAMERA_ERROR_INF__x sigthsCameraErrorInf
  ) {
    try {
      // 外部オブジェクトのDML操作は、ooAsync or ooImmediateで行う
      //Database.SaveResult sr = Database.updateAsync(sigthsCameraErrorInf);
      Database.SaveResult sr = Database.updateImmediate(sigthsCameraErrorInf);
      if (!sr.isSuccess()) {
        String locator = Database.getAsyncLocator(sr);
        System.debug(locator);
        return null;
      }
    } catch (Exception e) {
      System.debug(e.getMessage());
      return null;
    }

    return sigthsCameraErrorInf;
  }
}