force-app/main/default/objects/DEVICE_MNG__x/DEVICE_MNG__x.object-meta.xml
<CustomObject>
    <description>DEVICE_MNG</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>DEVICE_MNG</externalName>
    <label>機器管理</label>
</CustomObject>

force-app/main/default/objects/DEVICE_MNG__x/fields/device_mng_id__c.field-meta.xml
<CustomField>
    <fullName>device_mng_id__c</fullName>
    <description>device_mng_id</description>
    <externalDeveloperName>device_mng_id</externalDeveloperName>
    <label>機器管理ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/SIGHTS_CAMERA_INF__x.object-meta.xml
<CustomObject>
    <description>SIGHTS_CAMERA_INF</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>SIGHTS_CAMERA_INF</externalName>
    <label>Sightsカメラ情報</label>
</CustomObject>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/fields/device_mng_id__c.field-meta.xml
<CustomField>
    <fullName>device_mng_id__c</fullName>
    <description>device_mng_id</description>
    <externalDeveloperName>device_mng_id</externalDeveloperName>
    <label>機器管理</label>
    <length>36</length>
    <referenceTo>DEVICE_MNG__x</referenceTo>
    <relationshipLabel>Sightsカメラ情報</relationshipLabel>
    <relationshipName>sights_camera_inf_LKUP</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/fields/sights_camera_inf_id__c.field-meta.xml
<CustomField>
    <fullName>sights_camera_inf_id__c</fullName>
    <description>sights_camera_inf_id</description>
    <externalDeveloperName>sights_camera_inf_id</externalDeveloperName>
    <label>Sightsカメラ情報ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RMS_Util.cls
public with sharing class RMS_Util {
  /**
   * 機器管理レコードの取得
   * device_mng_id__c を使用したいため取得している
   *
   * @param recordId 画面表示している機器管理レコードのId
   * @return 画面表示している機器管理レコードList（1件のみ）
   */
  public static List<DEVICE_MNG__x> getDeviceMng(String recordId) {
    // prettier-ignore
    List<DEVICE_MNG__x> deviceMngList = [
        SELECT
          device_mng_id__c
        FROM
          DEVICE_MNG__x
        WHERE
          Id = :recordId
      ];
    return deviceMngList;
  }

  /**
   * Sightsカメラ情報レコードの取得
   * sights_camera_inf_id__c を使用したいため取得している
   *
   * @param deviceMng 画面表示している機器管理レコード
   * @return 画面表示している機器管理レコードに紐づくSightsカメラ情報レコードList（1件のみ）
   */
  public static List<SIGHTS_CAMERA_INF__x> getSightsCameraInfListByDeviceMngId(
    DEVICE_MNG__x deviceMng
  ) {
    // prettier-ignore
    List<SIGHTS_CAMERA_INF__x> sightsCameraInfList = [
        SELECT
          sights_camera_inf_id__c
        FROM
          SIGHTS_CAMERA_INF__x
        WHERE
          device_mng_id__c = :deviceMng.device_mng_id__c
      ];
    return sightsCameraInfList;
  }
}