force-app/main/default/objects/DEVICE_MNG__x/DEVICE_MNG__x.object-meta.xml
<CustomObject>
    <description>DEVICE_MNG</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>DEVICE_MNG</externalName>
    <label>機器管理</label>
</CustomObject>

force-app/main/default/objects/DEVICE_MNG__x/fields/device_mng_id__c.field-meta.xml
<CustomField>
    <fullName>device_mng_id__c</fullName>
    <description>device_mng_id</description>
    <externalDeveloperName>device_mng_id</externalDeveloperName>
    <label>機器管理ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_CameraLiveAuthMng__c/RMS_CameraLiveAuthMng__c.object-meta.xml
<CustomObject>
    <label>カメラ映像権限管理</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>カメラ映像権限管理名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_CameraLiveAuthMng__c/fields/browse_end_date__c.field-meta.xml
<CustomField>
    <fullName>browse_end_date__c</fullName>
    <defaultValue>NOW() +3</defaultValue>
    <label>閲覧終了日時</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RMS_CameraLiveAuthMng__c/fields/browse_str_date__c.field-meta.xml
<CustomField>
    <fullName>browse_str_date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>閲覧開始日時</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RMS_CameraLiveAuthMng__c/fields/operater_id__c.field-meta.xml
<CustomField>
    <fullName>operater_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>オペレーターID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>operater_id_LKUP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_CameraLiveAuthMng__c/fields/sights_camera_inf_id__c.field-meta.xml
<CustomField>
    <fullName>sights_camera_inf_id__c</fullName>
    <label>Sightsカメラ情報ID</label>
    <length>36</length>
    <referenceTo>SIGHTS_CAMERA_INF__x</referenceTo>
    <relationshipLabel>カメラ映像権限管理</relationshipLabel>
    <relationshipName>CameraLiveAuthMng_sights_camera_inf_LKUP</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/SIGHTS_CAMERA_INF__x.object-meta.xml
<CustomObject>
    <description>SIGHTS_CAMERA_INF</description>
    <externalDataSource>sights_dev_db</externalDataSource>
    <externalName>SIGHTS_CAMERA_INF</externalName>
    <label>Sightsカメラ情報</label>
</CustomObject>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/fields/device_mng_id__c.field-meta.xml
<CustomField>
    <fullName>device_mng_id__c</fullName>
    <description>device_mng_id</description>
    <externalDeveloperName>device_mng_id</externalDeveloperName>
    <label>機器管理</label>
    <length>36</length>
    <referenceTo>DEVICE_MNG__x</referenceTo>
    <relationshipLabel>Sightsカメラ情報</relationshipLabel>
    <relationshipName>sights_camera_inf_LKUP</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/SIGHTS_CAMERA_INF__x/fields/sights_camera_inf_id__c.field-meta.xml
<CustomField>
    <fullName>sights_camera_inf_id__c</fullName>
    <description>sights_camera_inf_id</description>
    <externalDeveloperName>sights_camera_inf_id</externalDeveloperName>
    <label>Sightsカメラ情報ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RMS_LiveCameraCtrl.cls
public with sharing class RMS_LiveCameraCtrl {
  public DEVICE_MNG__x currentDeviceMng { get; set; }
  public boolean isSightsCamera { get; set; } // 機器がSightsカメラかどうかのフラグ
  public boolean isCameraAuth { get; set; } // Sightsカメラ映像の閲覧権限があるかどうかのフラグ

  public RMS_LiveCameraCtrl() {
    // 画面に表示している機器管理レコードのIdを取得
    Id recordId = ApexPages.currentPage().getParameters().get('id');

    // 画面に表示している機器管理レコードを取得
    List<DEVICE_MNG__x> deviceMngList = RMS_Util.getDeviceMng(recordId);

    if (deviceMngList.size() != 1) {
      // 機器管理が取得出来なかった場合
      // ToDo: エラー処理
      return;
    } else {
      this.currentDeviceMng = deviceMngList[0];
    }

    // Sightsカメラ情報の取得
    List<SIGHTS_CAMERA_INF__x> sightsCameraInfList = RMS_Util.getSightsCameraInfListByDeviceMngId(
      this.currentDeviceMng
    );

    if (sightsCameraInfList.size() != 1) {
      // Sightsカメラが取得出来なかった場合（機器がSightsカメラ以外の場合）
      this.isSightsCamera = false;
      return;
    } else {
      this.isSightsCamera = true;
    }

    // カメラ映像権限取得
    List<RMS_CameraLiveAuthMng__c> cameraLiveAuthMngList = getCameraLiveAuthMngListByCameraInf(
      sightsCameraInfList[0]
    );
    if (cameraLiveAuthMngList.size() != 1) {
      // カメラ映像の権限が無い場合
      this.isCameraAuth = false;
      return;
    } else {
      // カメラ映像の権限がある場合
      this.isCameraAuth = true;
    }
  }

  /**
   * カメラ映像権限管理レコードの取得
   * device_mng_id__c を使用したいため取得している
   *
   * @param sightsCameraInf 画面表示している機器管理レコードに紐づくSightsカメラ情報レコード
   * @return Sightsカメラ情報レコードに紐づくSightsカメラ異常状態レコードList（1件のみ）
   */
  private static List<RMS_CameraLiveAuthMng__c> getCameraLiveAuthMngListByCameraInf(
    SIGHTS_CAMERA_INF__x sightsCameraInf
  ) {
    // 現在時刻
    Datetime now = datetime.now();

    // prettier-ignore
    List<RMS_CameraLiveAuthMng__c> cameraLiveAuthMngList = [
      SELECT
        Id
      FROM
        RMS_CameraLiveAuthMng__c
      WHERE
        sights_camera_inf_id__c = :sightsCameraInf.sights_camera_inf_id__c
        AND operater_id__c = :UserInfo.getUserId()
        AND browse_str_date__c <= :now
        AND browse_end_date__c >= :now
    ];
    return cameraLiveAuthMngList;
  }
}